// Canvas LMS Data - Auto-generated by canvas-sync.py
// Real data loads locally — not committed to public repo
// To connect: run canvas-sync.sh locally to generate real data

const CANVAS_DATA = {
  "last_sync": null,
  "courses": [],
  "upcoming_assignments": [],
  "missing_submissions": [],
  "announcements": [],
  "stats": {
    "total_courses": 0,
    "upcoming_assignments": 0,
    "missing_count": 0
  }
};

if (typeof window !== 'undefined') {
  window.CANVAS_DATA = CANVAS_DATA;
}
