// Canvas LMS Data - Auto-generated by canvas-sync.py
// Last sync: 2026-02-16 23:01

const CANVAS_DATA = {
  "last_sync": "2026-02-16T23:01:10.454442",
  "courses": [
    {
      "id": 1709824,
      "name": "AMERICAN LIT",
      "course_code": "ENGL-2250-008 (Spring 2026)",
      "term": "Spring 2026"
    },
    {
      "id": 1306857,
      "name": "INSY Undergrad Students",
      "course_code": "insy_undergrads",
      "term": "Student Development"
    },
    {
      "id": 1706362,
      "name": "INSY-3010-EA1 (Spring 2026)",
      "course_code": "INSY-3010-EA1 (Spring 2026)",
      "term": "Spring 2026"
    },
    {
      "id": 1706361,
      "name": "INSY-3020-001 (Spring 2026)",
      "course_code": "INSY-3020-001 (Spring 2026)",
      "term": "Spring 2026"
    },
    {
      "id": 1706363,
      "name": "INSY-3021-EA1 (Spring 2026)",
      "course_code": "INSY-3021-EA1 (Spring 2026)",
      "term": "Spring 2026"
    },
    {
      "id": 1549609,
      "name": "MECH Student Handbook",
      "course_code": "mech_handbook",
      "term": "Student Development"
    },
    {
      "id": 1707728,
      "name": "STAT-3600-100 (Spring 2026)",
      "course_code": "STAT-3600-100 (Spring 2026)",
      "term": "Spring 2026"
    }
  ],
  "upcoming_assignments": [
    {
      "id": 18863012,
      "name": "Lab #4 Fan Cat",
      "due_at": "2026-02-17T05:59:59Z",
      "points_possible": 100.0,
      "submission_types": [
        "online_upload"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "INSY-3021-EA1 (Spring 2026)",
      "course_id": 1706363
    },
    {
      "id": 18915222,
      "name": "Minor Reflection #6: Wheatley",
      "due_at": "2026-02-18T05:59:59Z",
      "points_possible": 5.0,
      "submission_types": [
        "online_text_entry"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "AMERICAN LIT",
      "course_id": 1709824
    },
    {
      "id": 18922127,
      "name": "HW7-section 2.2",
      "due_at": "2026-02-19T05:59:59Z",
      "points_possible": 10.0,
      "submission_types": [
        "online_upload"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "STAT-3600-100 (Spring 2026)",
      "course_id": 1707728
    },
    {
      "id": 18915224,
      "name": "Minor Reflection #7: Brown",
      "due_at": "2026-02-20T05:59:00Z",
      "points_possible": 5.0,
      "submission_types": [
        "online_text_entry"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "AMERICAN LIT",
      "course_id": 1709824
    },
    {
      "id": 18922128,
      "name": "HW8-Section 2.3",
      "due_at": "2026-02-23T05:59:00Z",
      "points_possible": 10.0,
      "submission_types": [
        "online_upload"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "STAT-3600-100 (Spring 2026)",
      "course_id": 1707728
    }
  ],
  "missing_submissions": [
    {
      "id": 18915222,
      "name": "Minor Reflection #6: Wheatley",
      "due_at": "2026-02-18T05:59:59Z",
      "points_possible": 5.0,
      "submission_types": [
        "online_text_entry"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "AMERICAN LIT",
      "course_id": 1709824
    },
    {
      "id": 18915224,
      "name": "Minor Reflection #7: Brown",
      "due_at": "2026-02-20T05:59:00Z",
      "points_possible": 5.0,
      "submission_types": [
        "online_text_entry"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "AMERICAN LIT",
      "course_id": 1709824
    },
    {
      "id": 18863012,
      "name": "Lab #4 Fan Cat",
      "due_at": "2026-02-17T05:59:59Z",
      "points_possible": 100.0,
      "submission_types": [
        "online_upload"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "INSY-3021-EA1 (Spring 2026)",
      "course_id": 1706363
    },
    {
      "id": 18922127,
      "name": "HW7-section 2.2",
      "due_at": "2026-02-19T05:59:59Z",
      "points_possible": 10.0,
      "submission_types": [
        "online_upload"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "STAT-3600-100 (Spring 2026)",
      "course_id": 1707728
    },
    {
      "id": 18922128,
      "name": "HW8-Section 2.3",
      "due_at": "2026-02-23T05:59:00Z",
      "points_possible": 10.0,
      "submission_types": [
        "online_upload"
      ],
      "has_submitted": false,
      "needs_grading": true,
      "course_name": "STAT-3600-100 (Spring 2026)",
      "course_id": 1707728
    }
  ],
  "announcements": [
    {
      "course_id": 1306857,
      "title": "Employer Events This Week",
      "posted_at": "2026-02-16T16:00:06Z",
      "url": "https://auburn.instructure.com/courses/1306857/discussion_topics/10529068"
    },
    {
      "course_id": 1709824,
      "title": "Week 7 Update: Overview of the Charles Brockden Brown Novella",
      "posted_at": "2026-02-13T20:00:01Z",
      "url": "https://auburn.instructure.com/courses/1709824/discussion_topics/10346523"
    },
    {
      "course_id": 1306857,
      "title": "E-DAY IS COMING \u2014 WE NEED YOU!",
      "posted_at": "2026-02-12T15:00:16Z",
      "url": "https://auburn.instructure.com/courses/1306857/discussion_topics/10528065"
    },
    {
      "course_id": 1706362,
      "title": "Practice Test...",
      "posted_at": "2026-02-11T21:08:52Z",
      "url": "https://auburn.instructure.com/courses/1706362/discussion_topics/10528110"
    },
    {
      "course_id": 1706361,
      "title": "Recordkeeping HW Answers",
      "posted_at": "2026-02-10T00:00:21Z",
      "url": "https://auburn.instructure.com/courses/1706361/discussion_topics/10521973"
    }
  ],
  "stats": {
    "total_courses": 7,
    "upcoming_assignments": 5,
    "missing_count": 5
  }
};

// For Forge integration
if (typeof window !== 'undefined') {
  window.CANVAS_DATA = CANVAS_DATA;
}
