// Auto-generated by usage-tracker — 2026-02-14 17:39 CST
const USAGE_DATA = {
  "timestamp": "2026-02-14T23:39:22Z",
  "timestampCST": "2026-02-14 17:39 CST",
  "date": "2026-02-14",
  "subscriptions": {
    "claudeMax": {
      "name": "Claude Max",
      "cost": 200,
      "period": "monthly",
      "provider": "anthropic",
      "notes": "Flat rate, unlimited tokens in session"
    },
    "chatgptPlus": {
      "name": "ChatGPT Plus (Codex)",
      "cost": 20,
      "period": "monthly",
      "provider": "openai",
      "notes": "Used for Codex CLI coding tasks"
    },
    "kimiK2": {
      "name": "Kimi K2.5",
      "cost": 19,
      "period": "monthly",
      "provider": "moonshot",
      "notes": "Sub-agent background tasks"
    }
  },
  "totalMonthlyCost": 239,
  "openclaw": {
    "sessionStats": {"sessions": [{"sessionId": "36419523-b42", "model": "claude-sonnet-4-5", "calls": 125, "inputTokens": 696, "outputTokens": 24866, "cacheReadTokens": 5948361, "cost": 6.1719, "lastActive": "2026-02-13T06:19:58.748036+00:00"}, {"sessionId": "53b6583a-0ca", "model": "claude-opus-4-6", "calls": 6, "inputTokens": 8, "outputTokens": 954, "cacheReadTokens": 103697, "cost": 0.2279, "lastActive": "2026-02-13T18:15:12.923054+00:00"}, {"sessionId": "55e86e04-975", "model": "claude-opus-4-6", "calls": 5, "inputTokens": 7, "outputTokens": 1102, "cacheReadTokens": 82391, "cost": 0.2259, "lastActive": "2026-02-13T20:01:44.313006+00:00"}, {"sessionId": "73276611-b7c", "model": "k2p5", "calls": 3, "inputTokens": 14695, "outputTokens": 769, "cacheReadTokens": 34048, "cost": 0, "lastActive": "2026-02-13T22:00:30.196548+00:00"}, {"sessionId": "a617d542-52a", "model": "claude-sonnet-4-5", "calls": 2, "inputTokens": 23, "outputTokens": 586, "cacheReadTokens": 16975, "cost": 0.0784, "lastActive": "2026-02-13T22:00:50.707315+00:00"}, {"sessionId": "aaa5776e-84b", "model": "claude-sonnet-4-5", "calls": 1049, "inputTokens": 2766, "outputTokens": 365991, "cacheReadTokens": 95553372, "cost": 72.6363, "lastActive": "2026-02-14T23:39:22.906848+00:00"}, {"sessionId": "d7dcd4e6-d7c", "model": "claude-opus-4-6", "calls": 5, "inputTokens": 7, "outputTokens": 891, "cacheReadTokens": 85796, "cost": 0.2184, "lastActive": "2026-02-13T15:47:01.719530+00:00"}], "totals": {"apiCalls": 1195, "inputTokens": 18202, "outputTokens": 395159, "cacheReadTokens": 101824640, "estimatedCost": 79.56}},
    "contextUsage": [{"key": "agent:main:main", "model": "claude-opus-4-6", "contextUsed": 87, "totalTokens": 173353, "maxTokens": 200000, "ageSeconds": 363173}, {"key": "agent:main:cron:2131c426-d479-4159-b0df-d288a644b97a", "model": "claude-sonnet-4-5", "contextUsed": 2, "totalTokens": 17186, "maxTokens": 1000000, "ageSeconds": 92337073}, {"key": "agent:main:cron:98de8520-0ce7-42ff-bdec-576eff748212", "model": "k2p5", "contextUsed": 7, "totalTokens": 18434, "maxTokens": 262144, "ageSeconds": 92367310}, {"key": "agent:main:cron:f37fc020-788a-4c22-92dd-d43c0446abad", "model": "claude-opus-4-6", "contextUsed": 13, "totalTokens": 25136, "maxTokens": 200000, "ageSeconds": 99545737}, {"key": "agent:main:discord:channel:1471662115885682729", "model": "claude-opus-4-6", "contextUsed": 29, "totalTokens": 57198, "maxTokens": 200000, "ageSeconds": 113100949}]
  },
  "vps": {
    "cpuPercent": 0,
    "memoryUsedMB": 2355,
    "memoryTotalMB": 3915,
    "memoryPercent": 60,
    "diskPercent": 40,
    "uptime": "1 week, 2 days, 5 hours, 7 minutes"
  },
  "weeklyReset": {
    "claudeMax": "Thursday 6:00 PM CST",
    "daysUntilReset": 5
  }
};
